### ISSUE TITLE
Create Mask Point Cloud sample

### ISSUE THREAD

**Issue by SatjaSivcev** [zivid/zivid-cpp-samples#125]
https://github.com/zivid/python-samples/blob/master/source/applications/advanced/mask_point_cloud.py

**Comment by robertkt1** [comment]
This can be closed? https://github.com/zivid/zivid-cpp-samples/blob/master/source/Applications/Advanced/MaskPointCloud/MaskPointCloud.cpp
@SatjaSivcev
