### ISSUE TITLE
Improve depth visualization in CreateDepthMap

### ISSUE THREAD

**Issue by SatjaSivcev** [zivid/zivid-cpp-samples#138]
From @dragly :
_Use a different colormap - jet is bad for a number of reasons. I think we should
use Virids for things like depth because it is going from dark to light. If we really
want rainbows, consider using Turbo. But I do not think there is a good reason to pick
a diverging colormap like jet or turbo for something like depth._
```
cv::Mat zJetColorMap;
cv::applyColorMap(z, zJetColorMap, cv::COLORMAP_JET);
```

**Comment by torbsorb** [comment]
Yes to Viridis; https://www.youtube.com/watch?v=xAoljeRJ3lU&feature=youtu.be
