### ISSUE TITLE
Add header with image and TOC similar to zivid-python

### ISSUE THREAD

**Issue by nedrebo** [zivid/zivid-cpp-samples#154]
Draw inspiration from https://github.com/zivid/zivid-python. However, when updating the image in  https://github.com/zivid/zivid-python it was noted that we should have a system that is easier to maintain. I propose to implement what was proposed in https://github.com/zivid/zivid-python/issues/111#issuecomment-758475065.

> Thx for updating this. I see that https://github.com/zivid/zivid-ros maintained by @apartridge is still using the old image. I have also proposed to @zivid/customer-success that they add headers with images and TOC to their repositories.
>
> I propose to place the image at a static URL, for example, https://www.zivid.com/hubfs/softwarefiles/images/zivid-generic-github-header.png. Then marketing can maintain that image and all repositories are updated automatically.
>
> @SatjaSivcev can you implement this system when you add a header to all your repositories, and also make a PR to https://github.com/zivid/zivid-python and https://github.com/zivid/zivid-ros?

**Comment by SatjaSivcev** [comment]
Fixed in #155

**Comment by nedrebo** [comment]
I see you did not do the TOC menu part like we have in https://github.com/zivid/zivid-python and https://github.com/zivid/zivid-ros. Can you elaborate on why? Fine if you don't want it, just curious.

**Comment by SatjaSivcev** [comment]
I missed that. Will do.
