### ISSUE TITLE
Error: Failed to load calibration from the camera because the camera has not been calibrated

### ISSUE THREAD

**Issue by danielcranston** [zivid/zivid-cpp-samples#189]
Hello, thanks for the awesome product!

I actually ran into this problem when using the ROS driver, but it seems to be a non-ROS issue so figured I'd make an issue here.

### Steps to reproduce:
1. Get hold of a Zivid 2 with firmware corresponding to SDK version `2.5.0+19fa6891-1_amd64`
2. Have SDK / `zivid_tools` version `2.3.0+a08763f1-1_amd64` installed on your Ubuntu 18.04 machine
3. run `ZividFirmwareUpdater` from your terminal to roll back the Zivid 2 firmware
4. run `ZividListCameras` from your terminal

You should observe the following:
```
Found 1 camera(s).
Error: Failed to load calibration from the camera because the camera has not been calibrated
```

And indeed, the camera does not seem to be usable (e.g. ROS driver dies, supposedly when constructing the `Zivid::Application`). I've had a look around the Zivid Knowledge Based and github repositories, but haven't found anything related to this error.

When bumping SDK / `zivid_tools` version up to `2.5.0+19fa6891-1_amd64` the issue disappears.

Granted, the situation is a bit contrived (although this was a real situation we ran into just recently), and the simple answer is "just make sure to use the latest SDK version!". Still, maybe it can be of use to you :slightly_smiling_face: 

So I guess my questions are
* What could cause this error to be triggered?
* Is there a way to recover from this without bumping the Zivid SDK / `zivid_tools` versions?

**Comment by SatjaSivcev** [comment]
Newer Zivid Two cameras come with Zivid Calibration Model 2.1.0. and are only compatible with SDK 2.4 or higher. More about ZCM can be found here: https://www.zivid.com/hubfs/Upgrade%20of%20Zivid%20Two%20calibration%20model.pdf?hsLang=en
