### ISSUE TITLE
Cannot find Zivid::Experimental::Calibration::detectFeaturePoints

### ISSUE THREAD

**Issue by Kanteloper** [zivid/zivid-cpp-samples#245]
Hi,

I used 'Zivid::Calibraion::detectFeaturePoints' function in SDK v2.8.1.
When I updated to SDK v2.9.0, there is a comment that the function is deprecated and I should use one of two functions.
- Zivid::Experimental::Calibration::detectFeaturePoints(const Zivid::Frame &frame)
- Zivid::Experimental::Calibration::detectFeaturePoints(Zivid::Camera &camera)

But two functions are not declared in 'Calibration.h' files.

![image](https://github.com/zivid/zivid-cpp-samples/assets/23246197/18eb8815-d1cc-46f3-97dc-127f68dfab4b)

**Comment by SatjaSivcev** [comment]
Hi,

These functions are declared indirectly via Zivid.h (Detector.h). Are you not able to run a program with this function? Can you share more details about the code and maybe a minimal reproducer?

**Comment by SatjaSivcev** [comment]
My bad, I was thinking about `ZIVID_CORE_EXPORT DetectionResult detectFeaturePoints(const PointCloud &cloud);`

The ones you are looking for are in `Zivid/Experimental/Calibration/InfieldCorrection.h`. I see now that this is a bin unintuitive so we will probably move it in Calibration.h where it more naturally belongs. Thanks for informing us!

**Comment by Kanteloper** [comment]
Thanks for answering me!
