### ISSUE TITLE
Missing NetworkConfiguration.cpp

### ISSUE THREAD

**Issue by tigercosmos** [zivid/zivid-cpp-samples#261]
According to the website, the example should be at "source/Camera/InfoUtilOther/NetworkConfiguration/NetworkConfiguration.cpp"

https://support.zivid.com/en/latest/api-reference/samples.html

![image](https://github.com/user-attachments/assets/83eaaeb2-56c7-4794-8e43-9c96f434cefc)

cc  @SatjaSivcev

**Comment by tigercosmos** [comment]
@SatjaSivcev  is there a way to get the camera's connected network interface?

**Comment by SatjaSivcev** [comment]
Hi @tigercosmos, can you try now? Here is the link: https://github.com/zivid/zivid-cpp-samples/blob/master/source/Camera/InfoUtilOther/NetworkConfiguration/NetworkConfiguration.cpp

We will have another sample soon, called "SetNetworkConfigurationAutomatically" or something similar. You as a user will provide the IP address of your network interface (PCI card or adapter) and subnet mask of your network, and the program will automatically configure all cameras it finds on the network to be in the same subnet.

**Comment by tigercosmos** [comment]
@SatjaSivcev  Is there a way to get the connected interface IP? Think about there are many LAN ports on a machine, and I just randomly plug in the device to any of them. Therefore, it will be helpful for the user to get the interface IP, so the device can be assigned to the desired IP later. It will be nice that the SDK supports this, because I don't want to use Avahi to just get the interface IP, which is overkill.

**Comment by SatjaSivcev** [comment]
Currently, Zivid SDK does not support this, but we are considering supporting it in the future. Thanks for your feedback!
