### ISSUE TITLE
Update to HDR::capture

### ISSUE THREAD

**Issue by torbsorb** [zivid/zivid-cpp-samples#70]
https://github.com/zivid/cpp-extra-samples/blob/54bf513806f72f2e782cc620ccd4e85db96d50b3/source/Camera/Basic/CaptureHDR/CaptureHDR.cpp#L24

is not our recommended method.

**Comment by torbsorb** [comment]
Note! This is a copy of the SDK version. Modification should be made in the SDK first.

**Comment by SatjaSivcev** [comment]
Can we close this @torbsorb? Not relevant in SDK 2.0 I think.
